name: Laravel Pint

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress


      - name: Run Pint (fail on violations)
        run: php vendor/bin/pint --test
        working-directory: ./siras10/
